[project]
name = "arc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.6.0",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "streamlit>=1.45.1",
    "tqdm>=4.67.1",
    "transformers>=4.51.3",
]
